# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
    #paths: "Source/*"
  #pull_request:
  #  branches: [ master ]
    
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"  
  build:
        
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    #- uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: |
        echo "Hello, world! Starting my custom action..."
        echo "ref: ${{ github.ref }}"
        echo "head_ref: ${{ github.head_ref }}"
        echo "base_ref: ${{ github.base_ref }}"
        echo "actor: ${{ github.actor }}"
        
      env:
        LOGIN: ${{ github.actor }}
        #echo "login: ${{ github.event.comment.user.login }}"
        #echo "id: ${{ github.event.comment.user.id }}"      
        #emailteste = ${{ github.event.comment.user.id }}+${{ github.event.comment.user.login }}@users.noreply.github.com
        #echo "email: $emailteste"

    - name: Checkout repo
      if: success()
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.comment-branch.outputs.ref }}
        persist-credentials: false

    # set up dotnet version
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    #- name: "dotnet restore"
    #  run: |
    #    dotnet restore
    #- name: Add dotnet-format problem matcher
    #  uses: xt0rted/dotnet-format-problem-matcher@v1

    - name: Restore dotnet tools
      uses: xt0rted/dotnet-tool-restore@v1

    - name: Run dotnet format
      uses: xt0rted/dotnet-format@v1
      with:
        # The GITHUB_TOKEN secret
        repo-token: ${{ secrets.MY_SECRET }} # repo-token: ${{ secrets.GITHUB_TOKEN }}
        #only-changed-files: true

    # Runs a set of commands using the runners shell
    - name: Commit files
      run: |
        echo "printing env : $LOGIN"
        
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git config user.name "${{ github.actor }}"
        git commit -a -m 'Automated dotnet-format update

    - name: Push changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        branch: ${{ steps.comment-branch.outputs.ref }}
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
